"""initial schema

Revision ID: c9f726552383
Revises:
Create Date: 2026-09-17 18:14:54.914522

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c9f726552383"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agents",
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("company_name", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("balance", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agents")),
        sa.UniqueConstraint("email", name=op.f("uq_agents_email")),
        sa.UniqueConstraint("username", name=op.f("uq_agents_username")),
    )
    op.create_table(
        "provider_call_logs",
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("operation", sa.String(length=64), nullable=False),
        sa.Column("request", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_call_logs")),
        comment="Audit: all calls to avia content providers",
    )
    op.create_table(
        "search_sessions",
        sa.Column("agent_id", sa.UUID(), nullable=True),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "DONE", "FAILED", "EXPIRED", name="searchstatus"),
            nullable=False,
        ),
        sa.Column("items_found", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_sessions")),
    )
    op.create_index(
        op.f("ix_search_sessions_agent_id"), "search_sessions", ["agent_id"], unique=False
    )
    op.create_index(op.f("ix_search_sessions_status"), "search_sessions", ["status"], unique=False)
    op.create_table(
        "balance_transactions",
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=True),
        sa.Column(
            "txn_type", sa.Enum("DEBIT", "CREDIT", "REFUND", name="transactiontype"), nullable=False
        ),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("balance_after", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("note", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("amount > 0", name=op.f("ck_balance_transactions_positive_amount")),
        sa.ForeignKeyConstraint(
            ["agent_id"], ["agents.id"], name=op.f("fk_balance_transactions_agent_id_agents")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_balance_transactions")),
        sa.UniqueConstraint("order_id", "txn_type", name="uq_balance_txns_order_type"),
    )
    op.create_index(
        op.f("ix_balance_transactions_agent_id"), "balance_transactions", ["agent_id"], unique=False
    )
    op.create_index(
        op.f("ix_balance_transactions_order_id"), "balance_transactions", ["order_id"], unique=False
    )
    op.create_table(
        "idempotency_keys",
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("scope", sa.String(length=64), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "status",
            sa.Enum("LOCKED", "COMPLETED", "FAILED", name="idempotencystatus"),
            nullable=False,
        ),
        sa.Column("response_status_code", sa.Integer(), nullable=True),
        sa.Column("response_body", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"], ["agents.id"], name=op.f("fk_idempotency_keys_agent_id_agents")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_idempotency_keys")),
        sa.UniqueConstraint("agent_id", "scope", "key", name="uq_idempotency_agent_scope_key"),
    )
    op.create_table(
        "orders",
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("search_id", sa.UUID(), nullable=True),
        sa.Column("offer_id", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum("BOOKED", "ISSUED", "CANCELLED", "FAILED", name="orderstatus"),
            nullable=False,
        ),
        sa.Column("total_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("offer_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("contact", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ticket_number", sa.String(length=16), nullable=True),
        sa.Column("ticket_file", sa.Text(), nullable=True),
        sa.Column("ticket_generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("total_amount > 0", name=op.f("ck_orders_positive_total_amount")),
        sa.ForeignKeyConstraint(
            ["agent_id"], ["agents.id"], name=op.f("fk_orders_agent_id_agents")
        ),
        sa.ForeignKeyConstraint(
            ["search_id"], ["search_sessions.id"], name=op.f("fk_orders_search_id_search_sessions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint("ticket_number", name=op.f("uq_orders_ticket_number")),
    )
    op.create_index(op.f("ix_orders_agent_id"), "orders", ["agent_id"], unique=False)
    op.create_index("ix_orders_agent_id_status", "orders", ["agent_id", "status"], unique=False)
    op.create_index(op.f("ix_orders_offer_id"), "orders", ["offer_id"], unique=False)
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)
    op.create_table(
        "order_passengers",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column(
            "pax_type", sa.Enum("ADULT", "CHILD", "INFANT", name="passengertype"), nullable=False
        ),
        sa.Column("first_name", sa.String(length=64), nullable=False),
        sa.Column("last_name", sa.String(length=64), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column("gender", sa.Enum("MALE", "FEMALE", name="gender"), nullable=True),
        sa.Column("citizenship", sa.String(length=3), nullable=True),
        sa.Column("doc_type", sa.Enum("PASSPORT", "ID_CARD", name="documenttype"), nullable=False),
        sa.Column("doc_number", sa.String(length=32), nullable=False),
        sa.Column("fare_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_passengers_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_passengers")),
    )
    op.create_table(
        "order_status_history",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column(
            "from_status",
            sa.Enum("BOOKED", "ISSUED", "CANCELLED", "FAILED", name="orderstatus"),
            nullable=True,
        ),
        sa.Column(
            "to_status",
            sa.Enum("BOOKED", "ISSUED", "CANCELLED", "FAILED", name="orderstatus"),
            nullable=False,
        ),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_status_history_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_status_history")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("order_status_history")
    op.drop_table("order_passengers")
    op.drop_index(op.f("ix_orders_status"), table_name="orders")
    op.drop_index(op.f("ix_orders_offer_id"), table_name="orders")
    op.drop_index("ix_orders_agent_id_status", table_name="orders")
    op.drop_index(op.f("ix_orders_agent_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_table("idempotency_keys")
    op.drop_index(op.f("ix_balance_transactions_order_id"), table_name="balance_transactions")
    op.drop_index(op.f("ix_balance_transactions_agent_id"), table_name="balance_transactions")
    op.drop_table("balance_transactions")
    op.drop_index(op.f("ix_search_sessions_status"), table_name="search_sessions")
    op.drop_index(op.f("ix_search_sessions_agent_id"), table_name="search_sessions")
    op.drop_table("search_sessions")
    op.drop_table("provider_call_logs")
    op.drop_table("agents")
    # ### end Alembic commands ###
